name: Check Code Quality + Test

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'process/**'
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Setup JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle and Test
        uses: gradle/gradle-build-action@v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          arguments: spec
